pluginDir: "/data/foundry/consumer_plugins/plugins"
database:
    host: localhost
    port: 27017
    db: discotest
    collection: records
    user: user
    pwd: "password"
mq:
    brokerURL: ${f_brokerURL:"tcp://localhost:61616?wireFormat.maxInactivityDuration=0"}

workflow:
    "Cinergi Workflow":
        - uuidGen
        - spatial
        - keyword
        - export
        - geoportal

consumers:
    - uuidGen:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.DocIDAssigner
         status: id_assigned
    - spatial:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.SpatialEnhancer2
         status: spatially_enhanced
    - keyword:
         class: org.neuinfo.foundry.consumers.jms.consumers.plugins.KeywordEnhancer2
         status: keyword_enhanced
         serviceURL: "http://ec-scigraph.sdsc.edu:9000"
         stopwordsUrl: "file:///data/cinergi/stopwords.txt"
         useNER: false
    - org:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.OrganizationEnhancer2"
         status: org_enhanced
    - export:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.WAFExporter"
         status: finished  
         outDirectory: "/tmp/waf"
    - geoportal:
         class: "org.neuinfo.foundry.consumers.jms.consumers.plugins.Geoportal2Exporter"
         status: finished
         gptURI: "http://geoportal:8080/geoportal/"
         elasticsearchIndex: metadata
         user: "gptadmin"
         password: "gptadmin"





